// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_jWE0b-RWDHdV8z0w8yYvqGPJtyCCVk',
    appId: '1:834171540193:web:e94cb72de764fdf1c49da0',
    messagingSenderId: '834171540193',
    projectId: 'clone-dakshin',
    authDomain: 'clone-dakshin.firebaseapp.com',
    storageBucket: 'clone-dakshin.appspot.com',
    measurementId: 'G-P9JMBW4B7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2ebqSrUFdBBzq-zKxwDBO94FL-uw6oA',
    appId: '1:834171540193:android:e59217f0962f66cfc49da0',
    messagingSenderId: '834171540193',
    projectId: 'clone-dakshin',
    storageBucket: 'clone-dakshin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJi9Q9L89S7jEf5Qkg55yomrV0kfErBs',
    appId: '1:834171540193:ios:9efc94c6b4b4d2c8c49da0',
    messagingSenderId: '834171540193',
    projectId: 'clone-dakshin',
    storageBucket: 'clone-dakshin.appspot.com',
    iosClientId: '834171540193-gqvvc5jdl2krlad73i0i5g8is14la6e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazoneClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADJi9Q9L89S7jEf5Qkg55yomrV0kfErBs',
    appId: '1:834171540193:ios:9efc94c6b4b4d2c8c49da0',
    messagingSenderId: '834171540193',
    projectId: 'clone-dakshin',
    storageBucket: 'clone-dakshin.appspot.com',
    iosClientId: '834171540193-gqvvc5jdl2krlad73i0i5g8is14la6e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazoneClone',
  );
}
